# Makefile generated by BNFC.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : TestDesmos

# Rules for building the parser.

AbsDesmos.hs LexDesmos.x ParDesmos.y PrintDesmos.hs TestDesmos.hs : desmos.cf
	bnfc --haskell desmos.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

TestDesmos : AbsDesmos.hs LexDesmos.hs ParDesmos.hs PrintDesmos.hs TestDesmos.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.

clean :
	-rm -f *.hi *.o *.log *.aux *.dvi

distclean : clean
	-rm -f AbsDesmos.hs AbsDesmos.hs.bak ComposOp.hs ComposOp.hs.bak DocDesmos.txt DocDesmos.txt.bak ErrM.hs ErrM.hs.bak LayoutDesmos.hs LayoutDesmos.hs.bak LexDesmos.x LexDesmos.x.bak ParDesmos.y ParDesmos.y.bak PrintDesmos.hs PrintDesmos.hs.bak SkelDesmos.hs SkelDesmos.hs.bak TestDesmos.hs TestDesmos.hs.bak XMLDesmos.hs XMLDesmos.hs.bak ASTDesmos.agda ASTDesmos.agda.bak ParserDesmos.agda ParserDesmos.agda.bak IOLib.agda IOLib.agda.bak Main.agda Main.agda.bak desmos.dtd desmos.dtd.bak TestDesmos LexDesmos.hs ParDesmos.hs ParDesmos.info ParDataDesmos.hs Makefile


# EOF
